"""V8 — Generate supplementary appendix LaTeX tables (standalone snippets).

Writes two \\input-able files into paper/ (does NOT edit main.tex):
  paper/tab_fdr_full.tex   — full 35-feature FDR table, Track A & Track B
                             side by side (mean IC, t-stat, BH-adjusted p,
                             rejection at q=0.10), sorted by Track B t-stat.
  paper/tab_ic_matrix.tex  — 9-fold x 7-model IC matrix for each track.

Run:
  python3 -u src/diagnostics/make_supp_tables.py
"""

from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent.parent
DATA = ROOT / "data" / "processed"
PAPER = ROOT / "paper"


def tex_feat(name: str) -> str:
    return r"\texttt{" + name.replace("_", r"\_") + "}"


def sig(v, d=3, plus=True):
    if pd.isna(v):
        return "--"
    s = f"{v:+.{d}f}" if plus else f"{v:.{d}f}"
    return s


def make_fdr_table():
    fdr = pd.read_parquet(DATA / "fdr_results.parquet")
    a = fdr[fdr.track == "track_a"].set_index("feature")
    b = fdr[fdr.track == "track_b"].set_index("feature")
    order = b.sort_values("t_stat", ascending=False).index.tolist()

    lines = []
    lines.append(r"% Auto-generated by src/diagnostics/make_supp_tables.py — do not edit by hand.")
    lines.append(r"\begin{table*}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Full per-feature FDR results for all 35 candidate features, "
                 r"Track~A and Track~B. Mean IC and $t$-statistic are computed across the "
                 r"9 expanding walk-forward folds ($t_f=\bar{\mathrm{IC}}_f/(s_f/\sqrt{9})$); "
                 r"$p_{\mathrm{BH}}$ is the Benjamini-Hochberg-adjusted $p$-value; "
                 r"$\checkmark$ marks rejection of the no-skill null at $q=0.10$. "
                 r"Features are ordered by Track~B $t$-statistic. "
                 r"Track~B rejects 25/35 features, Track~A 14/35.}")
    lines.append(r"\label{tab:fdr_full}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{l rrrc rrrc}")
    lines.append(r"\toprule")
    lines.append(r"& \multicolumn{4}{c}{Track~A} & \multicolumn{4}{c}{Track~B} \\")
    lines.append(r"\cmidrule(lr){2-5}\cmidrule(lr){6-9}")
    lines.append(r"Feature & $\bar{\mathrm{IC}}$ & $t$ & $p_{\mathrm{BH}}$ & rej.\ "
                 r"& $\bar{\mathrm{IC}}$ & $t$ & $p_{\mathrm{BH}}$ & rej.\ \\")
    lines.append(r"\midrule")
    for f in order:
        ra, rb = a.loc[f], b.loc[f]
        ca = r"$\checkmark$" if bool(ra["rejected"]) else ""
        cb = r"$\checkmark$" if bool(rb["rejected"]) else ""
        lines.append(
            f"{tex_feat(f)} & {sig(ra['mean_ic'])} & {sig(ra['t_stat'],2)} & "
            f"{sig(ra['bh_adj_p'],3,False)} & {ca} & "
            f"{sig(rb['mean_ic'])} & {sig(rb['t_stat'],2)} & "
            f"{sig(rb['bh_adj_p'],3,False)} & {cb} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table*}")
    (PAPER / "tab_fdr_full.tex").write_text("\n".join(lines) + "\n")
    print(f"Wrote paper/tab_fdr_full.tex ({len(order)} features)")


def make_ic_matrix():
    ic = pd.read_parquet(DATA / "ic_by_fold.parquet")
    models = ["ridge", "lasso", "logistic", "rf", "xgb", "lgbm", "ensemble"]
    mhead = {"ridge": "Ridge", "lasso": "Lasso", "logistic": "Logit",
             "rf": "RF", "xgb": "XGB", "lgbm": "LGBM", "ensemble": "Ens"}
    lines = []
    lines.append(r"% Auto-generated by src/diagnostics/make_supp_tables.py — do not edit by hand.")
    lines.append(r"\begin{table*}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Per-fold out-of-sample Spearman information coefficient (IC) "
                 r"for each of the seven models across the nine expanding walk-forward "
                 r"folds, for both tracks. The ensemble column is the equal-weight average "
                 r"used downstream. The 2020 fold reflects the COVID regime break.}")
    lines.append(r"\label{tab:ic_matrix}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{ll" + "r" * len(models) + "}")
    lines.append(r"\toprule")
    lines.append(r"Track & Fold & " + " & ".join(mhead[m] for m in models) + r" \\")
    lines.append(r"\midrule")
    for track, label in [("track_a", "A"), ("track_b", "B")]:
        sub = ic[ic.track == track].sort_values("fold")
        for i, (_, row) in enumerate(sub.iterrows()):
            tk = label if i == 0 else ""
            vals = " & ".join(sig(row[m]) for m in models)
            lines.append(f"{tk} & {int(row['fold'])} & {vals} \\\\")
        # mean row
        mean_vals = " & ".join(sig(sub[m].mean()) for m in models)
        lines.append(r"\cmidrule(lr){2-" + str(2 + len(models)) + "}")
        lines.append(f" & mean & {mean_vals} \\\\")
        if track == "track_a":
            lines.append(r"\midrule")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table*}")
    (PAPER / "tab_ic_matrix.tex").write_text("\n".join(lines) + "\n")
    print("Wrote paper/tab_ic_matrix.tex (9 folds x 7 models x 2 tracks)")


if __name__ == "__main__":
    make_fdr_table()
    make_ic_matrix()
