"""Emit paper/tab_baselines.tex from the results manifest.

This is the table the verdict is read against, and Reviewer 1's sixth point was
that its surrounding prose contradicted it. The prose is checked by assertions;
the table itself was still hand-typed, which is the same exposure that let
tab:rebal and tab:ta_fdr drift. Generating it closes that.

Run:
    python3 -u tools/gen_tab_baselines.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.manifest import get  # noqa: E402

OUT_TEX = ROOT / "paper" / "tab_baselines.tex"

IS, OOS = "IS_2013_21", "OOS_2022_24"

# (row label, manifest stem or None for the Track A / ML rows handled below)
BASELINES = [
    (r"Buy-and-Hold SPY$^\dagger$", "battery.baselines.Buy_and_Hold_SPY"),
    (r"Momentum L/S (12-1)", "battery.baselines.Momentum_L_S_12_1"),
    (r"Reversal L/S (5d)", "battery.baselines.Reversal_L_S_5d"),
]
ML = [
    (r"Na\"{i}ve ML, RF$^\ddagger$", "battery.ml_baseline.track_a.rf"),
    (r"Na\"{i}ve ML, XGBoost$^\ddagger$", "battery.ml_baseline.track_a.XGBoost"),
]


def need(key):
    v = get(key)
    if v is None:
        sys.exit(f"missing manifest entry: {key}; re-run the battery stages")
    return v


def main() -> None:
    rows = []
    for label, stem in BASELINES:
        rows.append(
            f"{label:<28} & ${need(f'{stem}.{IS}.gross_sr'):+.3f}$ & "
            f"${need(f'{stem}.{IS}.net_sr'):+.3f}$ & ${need(f'{stem}.{IS}.cost_drag'):.0f}$ & "
            f"${need(f'{stem}.{OOS}.gross_sr'):+.3f}$ & ${need(f'{stem}.{OOS}.net_sr'):+.3f}$ & "
            f"${need(f'{stem}.{OOS}.cost_drag'):.0f}$ \\\\"
        )
    # The ML stage records Sharpes only; its cost drag is not broken out.
    for label, stem in ML:
        rows.append(
            f"{label:<28} & ${need(f'{stem}.IS.gross_sr'):+.3f}$ & "
            f"${need(f'{stem}.IS.net_sr'):+.3f}$ & --- & "
            f"${need(f'{stem}.OOS.gross_sr'):+.3f}$ & ${need(f'{stem}.OOS.net_sr'):+.3f}$ & --- \\\\"
        )
    rows.append(
        r"Track~A (ours)               & "
        f"${need('backtest.track_a.is_gross_sharpe_weekly'):+.3f}$ & "
        f"$\\mathbf{{{need('backtest.track_a.is_net_sharpe_weekly'):+.3f}}}$ & "
        f"${need('backtest.track_a.is_cost_drag_bps_weekly'):.0f}$ & "
        f"${need('window.exploratory_2022_2024.track_a.gross_sharpe'):+.3f}$ & "
        f"$\\mathbf{{{need('window.exploratory_2022_2024.track_a.net_sharpe'):+.3f}}}$ & "
        f"${need('window.exploratory_2022_2024.track_a.cost_drag_bps'):.0f}$ \\\\"
    )

    nl = chr(10)
    OUT_TEX.write_text(f"""% AUTO-GENERATED by tools/gen_tab_baselines.py -- DO NOT EDIT
\\begin{{table}}[t]
\\centering
\\caption{{IS~(2013--2021) and exploratory OOS~(2022--24) performance of
         Track~A vs.\\ na\\"{{i}}ve baselines under weekly rebalancing,
         spread~$=3\\bps$, $\\eta=0.10$, and the same Screen~0 eligibility rule.
         Locked OOS 2025 columns omitted pending cost-sweep replication on
         the 144-day window.
         $\\dagger$~Buy-and-hold SPY has no AC cost and carries $\\beta\\!\\approx\\!1$;
         Track~A targets market-neutrality, so the comparison reflects
         different risk profiles.
         $\\ddagger$~Na\\"{{i}}ve ML is a RandomForest and an XGBoost model trained on
         all 30~features with neither FDR selection nor SHAP weighting,
         under identical costs and Screen~0. They are reported separately
         because averaging them hides the in-sample to out-of-sample collapse
         that is the point of the comparison; the stage records Sharpes only,
         so their drag is not broken out.
         Drag $=$ annualised total cost in bps~yr$^{{-1}}$.}}
\\label{{tab:baselines}}
\\begin{{adjustbox}}{{max width=\\textwidth}}
\\begin{{tabular}}{{lcccccc}}
\\toprule
& \\multicolumn{{3}}{{c}}{{In-Sample 2013--2021}} &
  \\multicolumn{{3}}{{c}}{{Exploratory OOS 2022--2024}} \\\\
\\cmidrule(lr){{2-4}}\\cmidrule(lr){{5-7}}
Strategy & Gross & Net & Drag &
           Gross & Net & Drag \\\\
         & SR    & SR  & (bps/yr) &
           SR    & SR  & (bps/yr) \\\\
\\midrule
{nl.join(rows)}
\\bottomrule
\\end{{tabular}}
\\end{{adjustbox}}
\\end{{table}}
""")
    print(f"wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
