"""Emit paper/tab_search_adjusted.tex from the search-adjusted FDR results.

The frozen family (m=30) and the search-enlarged family (m') are reported side
by side so a reader can see what the disclosed search costs in rejections.
Regenerate whenever the FDR stage reruns; the file is an artefact, not a source.

Run:
    python3 -u tools/gen_tab_search_adjusted.py
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IN_JSON = ROOT / "results" / "staging" / "fdr_search_adjusted.json"
LEDGER_CSV = ROOT / "results" / "search_ledger.csv"
OUT_TEX = ROOT / "paper" / "tab_search_adjusted.tex"
OUT_MACROS = ROOT / "paper" / "search_adjusted_macros.tex"

TRACK_LABEL = {"track_a": "Track~A", "track_b": "Track~B"}


def main() -> None:
    if not IN_JSON.exists():
        sys.exit(f"missing {IN_JSON}; run src/fdr/run_search_adjusted_fdr.py first")
    data = json.loads(IN_JSON.read_text())

    frozen = data["frozen_family"]
    enlarged = data["enlarged_family"]
    hlz = data["hlz_hurdle"]

    m_enlarged = int(enlarged["track_a"]["m_prime"])

    # The frozen family size comes from the ledger's own entry for it, so the
    # table cannot drift from the family the test actually used.
    ledger = list(csv.DictReader(LEDGER_CSV.open()))
    frozen_entries = [
        r for r in ledger
        if r["category"] == "feature_group" and r["status"] == "in_final"
    ]
    m_frozen = sum(int(r["n_hypotheses_added"]) for r in frozen_entries)
    if m_frozen <= 0:
        sys.exit(f"could not read the frozen family size from {LEDGER_CSV}")
    n_ledger = len(ledger)

    rows = []
    for track in ("track_a", "track_b"):
        rows.append(
            f"{TRACK_LABEL[track]} & {frozen[track]['bh_rejected']}/{m_frozen} & "
            f"{frozen[track]['bhy_rejected']}/{m_frozen} & "
            f"{enlarged[track]['bh_rejected']}/{m_enlarged} & "
            f"{enlarged[track]['bhy_rejected']}/{m_enlarged} & "
            f"{hlz[track]['n_survivors']}/{m_frozen} \\\\"
        )

    tex = f"""% AUTO-GENERATED by tools/gen_tab_search_adjusted.py -- DO NOT EDIT
\\begin{{table}}[htbp]
\\centering
\\caption{{Frozen versus search-enlarged FDR families ($q=0.10$). The frozen
family is the $m={m_frozen}$ specified features. The enlarged family adds every
candidate recorded in the research ledger ($m'={m_enlarged}$), with the
conservative value $p=1$ where no $p$-value under the current estimand is
recoverable. ``HLZ'' is the \\citet{{harvey2016and}} $|t|>3$ hurdle applied to
the frozen features.}}
\\label{{tab:search_adjusted}}
\\small
\\begin{{tabular}}{{lccccc}}
\\hline
 & \\multicolumn{{2}}{{c}}{{Frozen ($m={m_frozen}$)}} & \\multicolumn{{2}}{{c}}{{Enlarged ($m'={m_enlarged}$)}} & HLZ \\\\
Track & BH & BHY & BH & BHY & $|t|>3$ \\\\
\\hline
{chr(10).join(rows)}
\\hline
\\end{{tabular}}
\\end{{table}}
"""
    OUT_TEX.write_text(tex)

    macros = f"""% AUTO-GENERATED by tools/gen_tab_search_adjusted.py -- DO NOT EDIT
\\providecommand{{\\SearchLedgerRows}}{{{n_ledger}}}
\\renewcommand{{\\SearchLedgerRows}}{{{n_ledger}}}
\\providecommand{{\\SearchAdjustedFamily}}{{{m_enlarged}}}
\\renewcommand{{\\SearchAdjustedFamily}}{{{m_enlarged}}}
"""
    OUT_MACROS.write_text(macros)

    print(f"wrote {OUT_TEX}")
    print(f"wrote {OUT_MACROS}  (ledger rows={n_ledger}, m'={m_enlarged})")


if __name__ == "__main__":
    main()
