"""Emit paper/tab_rebal.tex from the results manifest.

Every cell of this table was hand-typed, and every cell drifted: it held
pre-correction values through two full re-runs while the prose around it was
updated. Assertions were added to pin the cells, which caught the drift but did
not stop it happening. Generating the table removes the failure mode instead of
detecting it.

Run:
    python3 -u tools/gen_tab_rebal.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.manifest import get  # noqa: E402

OUT_TEX = ROOT / "paper" / "tab_rebal.tex"

ROWS = [
    ("Daily  (1d)", "daily"),
    ("Weekly (5d)", "weekly"),
    ("Monthly(21d)", "monthly"),
]
DEPLOYED = "weekly"


def main() -> None:
    lines = []
    for label, freq in ROWS:
        to = get(f"backtest.track_a.is_annual_turnover_{freq}")
        gross = get(f"backtest.track_a.is_gross_sharpe_{freq}")
        net = get(f"backtest.track_a.is_net_sharpe_{freq}")
        net_ann = get(f"backtest.track_a.is_net_annual_pct_{freq}")
        drag = get(f"backtest.track_a.is_cost_drag_bps_{freq}")
        for name, v in (("turnover", to), ("gross", gross), ("net", net),
                        ("net annual", net_ann), ("drag", drag)):
            if v is None:
                sys.exit(f"missing manifest entry for the {freq} {name}; "
                         f"run tools/record_synthesis.py first")
        bold = (lambda s: f"$\\mathbf{{{s}}}$") if freq == DEPLOYED else (lambda s: f"${s}$")
        lines.append(
            f"{label} & {to:.1f} & {bold(f'{gross:+.3f}')} & {bold(f'{net:+.3f}')} "
            f"& ${net_ann:+.1f}$ & ${drag:.0f}$ \\\\"
        )

    nl = chr(10)
    OUT_TEX.write_text(f"""% AUTO-GENERATED by tools/gen_tab_rebal.py -- DO NOT EDIT
\\begin{{table}}[t]
\\centering
\\caption{{Track~A IS Performance vs.\\ Rebalancing Frequency
         (Spread~$=3\\bps$, $\\eta=0.10$, 2013--2021).
         Source: \\texttt{{sensitivity\\_3d.parquet}} via the results manifest.}}
\\label{{tab:rebal}}
\\begin{{tabular}}{{lccccc}}
\\toprule
Frequency & Annual TO & Gross SR & Net SR & Net Ann.\\ & Drag \\\\
          & ($\\times$) & & & (\\%) & (bps/yr) \\\\
\\midrule
{nl.join(lines)}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
""")
    print(f"wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
