"""Emit paper/tab_oos.tex and paper/tab_capacity.tex from the results manifest.

Both were hand-typed. tab:oos carries the four window results the verdict is
stated in, and tab:capacity repeats the in-sample gross Sharpe on every row, so
a change to the deployed book has to be retyped in eight places. That is the
arrangement that has now produced stale tables three times.

Run:
    python3 -u tools/gen_tab_windows.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.manifest import get  # noqa: E402

OUT_OOS = ROOT / "paper" / "tab_oos.tex"
OUT_CAP = ROOT / "paper" / "tab_capacity.tex"


def need(key):
    v = get(key)
    if v is None:
        sys.exit(f"missing manifest entry: {key}")
    return v


def windows_table() -> None:
    rows = []

    rows.append(
        "IS 2013--2021         & 2267 & "
        f"${need('backtest.track_a.is_gross_sharpe_weekly'):+.3f}$ & "
        f"${need('backtest.track_a.is_net_sharpe_weekly'):+.3f}$ & "
        f"${need('backtest.track_a.is_net_annual_pct_weekly'):+.1f}$ & "
        f"${need('backtest.track_a.is_cost_drag_bps_weekly'):.0f}$ & "
        f"${need('backtest.track_a.is_annual_turnover_weekly'):.1f}\\times$ \\\\"
    )
    for label, stem, days in (
        ("Exploratory 2022--24  ", "window.exploratory_2022_2024.track_a", 753),
        ("Locked OOS 2025 (Jan--Jul)", "window.locked_oos_2025.track_a", 144),
    ):
        rows.append(
            f"{label} & {days} & ${need(f'{stem}.gross_sharpe'):+.3f}$ & "
            f"${need(f'{stem}.net_sharpe'):+.3f}$ & "
            f"${need(f'{stem}.net_annual_pct'):+.1f}$ & "
            f"${need(f'{stem}.cost_drag_bps'):.0f}$ & "
            f"${need(f'{stem}.annual_turnover'):.1f}\\times$ \\\\"
        )
    # The forward window is the single pre-committed touch, so it is set in bold.
    f_net = need("forward.track_a.net_sharpe")
    rows.append(
        "\\textbf{Forward 2025-08--2026-03} & "
        f"{int(need('forward.track_a.n_days'))} & "
        f"$\\mathbf{{{need('forward.track_a.gross_sharpe'):+.3f}}}$ & "
        f"$\\mathbf{{{f_net:+.3f}}}$ & "
        f"${need('forward.track_a.net_annual_pct'):+.1f}$ & "
        f"${need('forward.track_a.cost_drag_bps'):.0f}$ & "
        f"${need('forward.track_a.annual_turnover'):.1f}\\times$ \\\\"
    )

    nl = chr(10)
    OUT_OOS.write_text(f"""% AUTO-GENERATED by tools/gen_tab_windows.py -- DO NOT EDIT
\\begin{{table}}[t]
\\centering
\\caption{{Track~A across every evaluation window, under the deployed
         configuration (weekly rebalancing, spread~$=3\\bps$, $\\eta=0.10$,
         one cost model). The forward window is the single pre-committed
         touch of Section~\\ref{{sec:forward}}.}}
\\label{{tab:oos}}
\\begin{{adjustbox}}{{max width=\\textwidth}}
\\begin{{tabular}}{{lcccccc}}
\\toprule
Window & Days & Gross SR & Net SR & Ann.\\ Net\\% & Drag (bps/yr) & Turnover \\\\
\\midrule
{nl.join(rows)}
\\bottomrule
\\end{{tabular}}
\\end{{adjustbox}}
\\end{{table}}
""")
    print(f"wrote {OUT_OOS}")


def capacity_table() -> None:
    rows = []
    for label, tag in (("\\$10M ", "aum_10M"), ("\\$50M ", "aum_50M"),
                       ("\\$100M", "aum_100M"), ("\\$500M", "aum_500M")):
        stem = f"backtest.track_a.capacity.{tag}"
        net = need(f"{stem}.net_sharpe")
        cell = f"$\\mathbf{{{net:+.3f}}}$" if tag == "aum_100M" else f"${net:+.3f}$"
        rows.append(
            f"{label} & ${need(f'{stem}.gross_sharpe'):+.3f}$ & {cell} & "
            f"${need(f'{stem}.net_annual') * 100:+.2f}$ & "
            f"${need(f'{stem}.cost_drag_bps'):.0f}$ \\\\"
        )

    nl = chr(10)
    OUT_CAP.write_text(f"""% AUTO-GENERATED by tools/gen_tab_windows.py -- DO NOT EDIT
\\begin{{table}}[t]
\\centering
\\caption{{Track~A IS net performance vs.\\ deployed capital
         (weekly rebalancing, spread~$=3\\bps$, $\\eta=0.10$, 2013--2021).
         Gross Sharpe and turnover are invariant to AUM; only the
         size-dependent impact term changes. The deployed size is \\$100M.}}
\\label{{tab:capacity}}
\\begin{{tabular}}{{lcccc}}
\\toprule
AUM & Gross SR & Net SR & Net Ann.\\ (\\%) & Drag (bps/yr) \\\\
\\midrule
{nl.join(rows)}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
""")
    print(f"wrote {OUT_CAP}")


if __name__ == "__main__":
    windows_table()
    capacity_table()
