"""Emit paper/tab_ta_fdr.tex and paper/ta_fdr_macros.tex from the v3 TA-FDR run.

The table was hand-typed once. The v3 run then replaced the null construction
and every p-value in it, but the table kept the v2 numbers, which are precisely
the ones Reviewer 1 cited as evidence that the old null was invalid. The table
is an artefact now, not a source: regenerate it whenever the TA-FDR stage runs.

Both the net and the cost-blind p-value are shown. Their difference is the part
of the verdict that costs are responsible for, which is the whole point of the
test, and showing only one column is what let the two vintages hide from each
other.

Run:
    python3 -u tools/gen_tab_ta_fdr.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.manifest import get  # noqa: E402

IN_PARQUET = ROOT / "data" / "processed" / "ta_fdr_v3.parquet"
IN_SUMMARY = ROOT / "results" / "staging" / "ta_fdr_v3_summary.json"
OUT_TEX = ROOT / "paper" / "tab_ta_fdr.tex"
OUT_MACROS = ROOT / "paper" / "ta_fdr_macros.tex"

N_SHOWN = 5


def tex_feature(name: str) -> str:
    return "\\texttt{" + name.replace("_", "\\_") + "}"


def main() -> None:
    if not IN_PARQUET.exists():
        sys.exit(f"missing {IN_PARQUET}; run src/backtest/run_ta_fdr.py --B 2000 first")
    df = pd.read_parquet(IN_PARQUET)
    summary = json.loads(IN_SUMMARY.read_text())

    bh_ic = set(get("fdr.track_a.selected_features_bh"))
    n_features = len(df[df["track"] == "track_a"])
    threshold = 0.10 / n_features
    B = int(summary["B"])
    block = int(summary["block_length"])

    # The five closest to rejection, so a reader can see the margin rather than
    # a selection of comfortable rows.
    shown = df[df["track"] == "track_a"].nsmallest(N_SHOWN, "p_net")

    rows = []
    for r in shown.itertuples():
        mark = "\\checkmark" if r.feature in bh_ic else ""
        rows.append(
            f"{tex_feature(r.feature)} & ${r.mean_net * 1e4:.3f}$ & "
            f"${r.p_net:.3f}$ & ${r.p_gross:.3f}$ & {mark} \\\\"
        )

    counts = []
    for track, label in (("track_a", "Track~A"), ("track_b", "Track~B")):
        s = summary["tracks"][track]
        counts.append(
            f"\\multicolumn{{2}}{{l}}{{TA-FDR rejections ({label})}} & "
            f"{s['n_bh_net']} / {n_features} & {s['n_bh_gross']} / {n_features} & \\\\"
        )

    bh_ic_a = int(get("fdr.track_a.n_selected_bh"))
    bh_ic_b = int(get("fdr.track_b.n_selected_bh"))
    counts.append(
        f"\\multicolumn{{2}}{{l}}{{BH-IC rejections (Track~A)}} & "
        f"\\multicolumn{{2}}{{c}}{{{bh_ic_a} / {n_features}}} & \\\\"
    )
    counts.append(
        f"\\multicolumn{{2}}{{l}}{{BH-IC rejections (Track~B)}} & "
        f"\\multicolumn{{2}}{{c}}{{{bh_ic_b} / {n_features}}} & \\\\"
    )

    nl = chr(10)
    tex = f"""% AUTO-GENERATED by tools/gen_tab_ta_fdr.py -- DO NOT EDIT
\\begin{{table}}[t]
\\centering
\\caption{{TA-FDR results: the {N_SHOWN} Track~A features with the smallest
         net $p$-values, that is, the closest to a tradable claim.
         $\\bar r^{{\\mathrm{{net}}}}$ is the IS mean daily net return in basis
         points (\\$100M AUM, spread $3\\bps$, $\\eta=0.10$), the test statistic
         $T_f$.
         $p^{{\\mathrm{{net}}}}$ is the one-sided $p$-value against the recentred
         joint block-bootstrap null ($B={B:,}$, mean block ${block}$~days);
         $p^{{\\mathrm{{blind}}}}$ is the cost-blind companion computed on the same
         draws, so the gap between the two columns is what costs are responsible
         for. $p^{{\\mathrm{{net}}}} \\geq p^{{\\mathrm{{blind}}}}$ holds on every
         feature, the containment machine-checked in Lean~4.
         BH threshold at rank~1: $q/m={threshold:.4f}$; every $p^{{\\mathrm{{net}}}}$
         is two orders of magnitude above it.
         BH-IC marks IC-based BH rejection from
         Section~\\ref{{subsec:fdr_results}}.}}
\\label{{tab:ta_fdr}}
\\begin{{tabular}}{{lcccc}}
\\toprule
Feature & $\\bar r^{{\\mathrm{{net}}}}$ (bps/day) & $p^{{\\mathrm{{net}}}}$ & $p^{{\\mathrm{{blind}}}}$ & BH-IC \\\\
\\midrule
{nl.join(rows)}
\\midrule
& & net & cost-blind & \\\\
{nl.join(counts)}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    OUT_TEX.write_text(tex)

    a = df[df["track"] == "track_a"]
    b = df[df["track"] == "track_b"]
    macros = f"""% AUTO-GENERATED by tools/gen_tab_ta_fdr.py -- DO NOT EDIT
\\providecommand{{\\TaFdrB}}{{{B:,}}}
\\renewcommand{{\\TaFdrB}}{{{B:,}}}
\\providecommand{{\\TaFdrBlock}}{{{block}}}
\\renewcommand{{\\TaFdrBlock}}{{{block}}}
\\providecommand{{\\TaFdrThreshold}}{{{threshold:.4f}}}
\\renewcommand{{\\TaFdrThreshold}}{{{threshold:.4f}}}
\\providecommand{{\\TaFdrMinPnetA}}{{{a['p_net'].min():.3f}}}
\\renewcommand{{\\TaFdrMinPnetA}}{{{a['p_net'].min():.3f}}}
\\providecommand{{\\TaFdrMinPblindA}}{{{a['p_gross'].min():.3f}}}
\\renewcommand{{\\TaFdrMinPblindA}}{{{a['p_gross'].min():.3f}}}
\\providecommand{{\\TaFdrMinPnetB}}{{{b['p_net'].min():.3f}}}
\\renewcommand{{\\TaFdrMinPnetB}}{{{b['p_net'].min():.3f}}}
\\providecommand{{\\TaFdrMinPblindB}}{{{b['p_gross'].min():.3f}}}
\\renewcommand{{\\TaFdrMinPblindB}}{{{b['p_gross'].min():.3f}}}
"""
    OUT_MACROS.write_text(macros)

    print(f"wrote {OUT_TEX}")
    print(f"wrote {OUT_MACROS}  (B={B}, min p_net A={a['p_net'].min():.4f})")


if __name__ == "__main__":
    main()
