#!/usr/bin/env python3
"""
tools/regenerate_numbers.py — Emit \newcommand macros from the manifest.

Reads results/manifest/manifest.json and writes paper/generated_numbers.tex,
one \newcommand per manifest entry.  Key sanitisation turns dot-namespaced
metric keys into valid LaTeX macro names (CamelCase, no special chars).

The manuscript can then do:
    \\input{generated_numbers}
and reference, e.g.:
    The net Sharpe is \\OosTrackBNetSharpe.

Idempotent: safe to run multiple times; always overwrites generated_numbers.tex.

Usage:
    python3 tools/regenerate_numbers.py
    python3 tools/regenerate_numbers.py --manifest path/to/manifest.json
    python3 tools/regenerate_numbers.py --out paper/generated_numbers.tex
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = ROOT / "results" / "manifest" / "manifest.json"
DEFAULT_OUT = ROOT / "paper" / "generated_numbers.tex"

# Float display precision
FLOAT_PRECISION = 4


def sanitise_key(key: str) -> str:
    """Convert a dot-namespaced manifest key to a valid LaTeX macro name.

    Rules:
      - Split on dots and underscores; CamelCase each word.
      - Remove any remaining non-alpha characters.
      - Prepend 'M' if the result starts with a digit (LaTeX macros cannot
        start with a digit).

    Examples:
        "oos.trackB.net_sharpe"  -> "OosTrackBNetSharpe"
        "fdr.trackA.n_selected"  -> "FdrTrackANSelected"
        "pbo.trackB.probability" -> "PboTrackBProbability"
    """
    # Split on dots and underscores
    parts = re.split(r"[._\-]+", key)
    camel = "".join(p.capitalize() for p in parts if p)
    # Remove any remaining non-alpha characters
    camel = re.sub(r"[^A-Za-z]", "", camel)
    # LaTeX macro names must start with a letter
    if camel and camel[0].isdigit():
        camel = "M" + camel
    return camel if camel else "UnknownKey"


def format_value(value) -> str:
    """Format a manifest value for LaTeX output."""
    if isinstance(value, float):
        # Avoid scientific notation for typical numeric ranges
        if abs(value) < 1e6 and (value == 0 or abs(value) > 1e-4):
            return f"{value:.{FLOAT_PRECISION}f}"
        else:
            return f"{value:.{FLOAT_PRECISION}e}"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        return ", ".join(format_value(v) for v in value)
    # str or other — escape LaTeX special chars
    s = str(value)
    for char, replacement in [
        ("\\", r"\textbackslash{}"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("&", r"\&"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]:
        s = s.replace(char, replacement)
    return s


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate paper/generated_numbers.tex from manifest."
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help=f"Path to manifest.json (default: {DEFAULT_MANIFEST})",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help=f"Output .tex file (default: {DEFAULT_OUT})",
    )
    args = parser.parse_args()

    if not args.manifest.exists():
        print(f"[WARN] Manifest not found: {args.manifest}", file=sys.stderr)
        print("[WARN] Writing empty generated_numbers.tex (no manifest entries).")
        manifest: dict = {}
    else:
        with open(args.manifest, "r", encoding="utf-8") as f:
            manifest = json.load(f)

    # Ensure output directory exists
    args.out.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("% generated_numbers.tex — AUTO-GENERATED by tools/regenerate_numbers.py")
    lines.append(f"% Source: {args.manifest}")
    lines.append(f"% Generated: {datetime.now(timezone.utc).isoformat()}")
    lines.append("% DO NOT EDIT BY HAND — re-run tools/regenerate_numbers.py")
    lines.append("%")
    lines.append("% Usage in main.tex:")
    lines.append(r"%   \input{generated_numbers}")
    lines.append(r"%   ... The net Sharpe ratio was \OosTrackBNetSharpe.")
    lines.append("%")

    macro_names: list[str] = []
    collisions: dict[str, list[str]] = {}
    skipped = 0

    # Sort for deterministic output
    for key in sorted(manifest.keys()):
        entry = manifest[key]
        value = entry.get("value") if isinstance(entry, dict) else entry

        if value is None:
            skipped += 1
            continue

        macro = sanitise_key(key)

        # Detect collisions
        if macro in collisions:
            collisions[macro].append(key)
        else:
            collisions[macro] = [key]

        stage = entry.get("stage", "unknown") if isinstance(entry, dict) else "unknown"
        track = entry.get("track") if isinstance(entry, dict) else None
        universe = entry.get("universe") if isinstance(entry, dict) else None
        spec_hash = entry.get("spec_hash", "?") if isinstance(entry, dict) else "?"

        comment_parts = [f"key={key}", f"stage={stage}"]
        if track:
            comment_parts.append(f"track={track}")
        if universe:
            comment_parts.append(f"universe={universe}")
        comment_parts.append(f"spec={spec_hash[:8]}")

        lines.append("")
        lines.append(f"% {' | '.join(comment_parts)}")
        lines.append(f"\\providecommand{{\\{macro}}}{{{format_value(value)}}}")
        # Use renewcommand to allow re-running without error
        lines.append(f"\\renewcommand{{\\{macro}}}{{{format_value(value)}}}")

        macro_names.append(macro)

    lines.append("")
    lines.append("% end of generated_numbers.tex")

    # Report any macro name collisions
    collision_keys = {m: ks for m, ks in collisions.items() if len(ks) > 1}
    if collision_keys:
        print("[WARN] Macro name collisions detected (multiple keys map to same macro):")
        for macro, keys_list in collision_keys.items():
            print(f"  \\{macro} <- {keys_list}")
        print("  The last key in sorted order wins. Consider renaming manifest keys.")

    # Write output
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    n_macros = len(macro_names)
    print(f"[OK] Wrote {n_macros} macro(s) to {args.out}")
    if skipped:
        print(f"[INFO] Skipped {skipped} entries with null values.")
    if collision_keys:
        print(f"[WARN] {len(collision_keys)} macro name collision(s) — see above.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
